name: Tweet

on:
  schedule:
    - cron: '0 20 * * *' # At 00:00

jobs:
  build:
    runs-on: macos-latest
    steps:

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python3 -m pip install --upgrade pip
          pip freeze > requirements.txt
          pip install -r requirements.txt

      - name: run python script # runs main.py
        uses: actions/checkout@v3
        env:
          consumer_key: ${{ secrets.CONSUMER_KEY }}
          consumer_secret: ${{ secrets.CONSUMER_SECRET }}
          access_token: ${{ secrets.ACCESS_TOKEN }}
          access_token_secret: ${{ secrets.ACCESS_TOKEN_SECRET }}
      - run: python3 main.py
